# Generated by Django 2.1.3 on 2018-11-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0004_auto_20181119_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='employee',
            field=models.CharField(default='', max_length=50),
        ),
    ]
