# Generated by Django 2.1.3 on 2018-11-19 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0006_auto_20181119_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmployeeUser',
        ),
    ]
