# Generated by Django 2.1.3 on 2018-11-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0008_employeeuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeuser',
            old_name='user',
            new_name='username',
        ),
    ]
