# Generated by Django 2.1.3 on 2018-11-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0009_auto_20181119_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeuser',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
