# Generated by Django 2.1.3 on 2018-11-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0010_auto_20181119_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='search',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
