# Generated by Django 2.1.3 on 2018-11-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0011_fine_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fine',
            name='search',
        ),
    ]
