# Generated by Django 2.1.3 on 2018-11-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0013_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delete',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeeuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='employeeuser',
            name='id',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fine',
            name='id',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Delete',
        ),
    ]
