# Generated by Django 2.1.3 on 2018-11-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0014_auto_20181121_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeuser',
            name='employee_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fine',
            name='employee_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
