# Generated by Django 2.1.3 on 2018-11-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0015_auto_20181121_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employeeuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='employeeuser',
            name='name',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
